addons:
  apt_packages:
    - lib32z1
    - lib32stdc++6
    - p7zip-full
    - rsync

language: c

env:
  - SOURCEMOD=1.9
  - SOURCEMOD=1.10

script:
    - 'if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then bash ci/build.sh $SOURCEMOD $TRAVIS_BRANCH ${TRAVIS_COMMIT::7}; else bash ci/test.sh $SOURCEMOD $TRAVIS_BRANCH ${TRAVIS_COMMIT::7}; fi'
